### ISSUE TITLE
ppt8 9

### ISSUE THREAD

**Issue by wchan0409** [RTS-Road-Through-Sogang/Server#31]
## Description
공통 필수와 공통 선택을 뽑아주는데, 이때 Category detail에 따라서 구분하여 serialize해서 뽑아준다

## To-do
- [ ] User의 student_year를 참조하여 category_d 21을 참조해야되는지, category_d 22를 참조해야되는지를 정하고 그 field값이 내가 원하는 category detail인 과목들을 (예: 서강인성을 category detail로 갖고 있는 과목) serialize 해주기
- [ ] 위의 것들을 serialize해줬으면 각 category detail의 이수 학점을 charfield로 추가해서 위의 serializer와 함께 serialize 해주기
- [ ] 공통필수인것들은 공통필수인것들끼리 공통선택은 공통선택인것들끼리 serialize해주기
- [ ] 공통선택도 반복
